title: ""
author: pabramber01
copyright: "2024"
logo: "histopathologic_cancer_detection/input/images/logo.png"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

execute:
  execute_notebooks: auto
  cache: "_build/.jupyter_cache"
  exclude_patterns: ["*"]
  timeout: -1
  run_in_temp: false
  allow_errors: false
  stderr_output: remove-warn

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
  myst_dmath_double_inline: true

html:
  favicon: "histopathologic_cancer_detection/input/images/logo.png"
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: false
  use_multitoc_numbering: true
  extra_footer: "Apache 2.0 license"
  google_analytics_id: ""
  home_page_in_navbar: false
  baseurl: "https://pabramber01.github.io/histopathologic-cancer-detection"
  comments:
    hypothesis: false
    utterances: false
  analytics:
  announcement: ""

latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true

launch_buttons:
  notebook_interface: classic
  binderhub_url: ""
  jupyterhub_url: ""
  thebe: false
  colab_url: ""

repository:
  url: https://github.com/pabramber01/histopathologic-cancer-detection
  path_to_book: "./"
  branch: main

sphinx:
  extra_extensions:
  local_extensions:
  recursive_update: false
  config:
